language: node_js
node_js:
  - '10'
cache:
  directories:
    - 'node_modules'
script:
  - yarn test:unit
  - yarn build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_API_KEY
  local_dir: build
  keep_history: true
  on:
    branch: dev
