export const RESTART_CURRENCY = 'restartCurrency'
export const SELECT_MACHINE = 'selectMachine'
export const UPDATE_BLOCK = 'updateBlock'
export const PLAY_GAME = 'playGame'
export const TICK = 'tick'
